### ISSUE TITLE
Is there a way to use Marker Clustering

### ISSUE THREAD

**Issue by yanqui92** [ng2-ui/map#104]
Hi I wanted to know if I can use this: 
https://developers.google.com/maps/documentation/javascript/marker-clustering
with this package.

**Comment by allenhwkim** [comment]
Currently, this feature is not implemented since this is not a Google maps API 3 official feature. 

However, PR would be highly appreciated.

**Comment by allenhwkim** [comment]
Anyone who is interested in OpenLayers clustering, please take a look this. https://rawgit.com/allenhwkim/react-openlayers/master/app/index.html#/custom/earthquake-clusters

**Comment by viztastic** [comment]
@allenhwkim Google seem to now document it as a [standard feature](https://developers.google.com/maps/documentation/javascript/marker-clustering) of their maps API using this [utility](https://github.com/googlemaps/v3-utility-library/blob/master/README.md) of theirs 

Would be great if we could integrate this into the library. I'd be happy to help with documentation  or your sites UX (as I'm not a great module developer!)

**Comment by kapocius** [comment]
@allenhwkim so is this in the works maybe?

**Comment by allenhwkim** [comment]
@kapocius It's not still under development since marker cluster is not a standard feature, but a community code.

**Comment by hesama110** [comment]
hi @allenhwkim do you have any idea how i can use custom-marker as cluster marker? 
in my map i have some markers they need to be cluster and with hove show list of markers and with click on that zoom, do you have any solution ?

**Comment by jorgelub12** [comment]
Any fix on this ?

**Comment by aitboudad** [comment]
well it can be done easily, here is a working example: https://stackblitz.com/edit/angular-jbp2yc

**Comment by jorgelub12** [comment]
@aitboudad  your link doesn't show the cluster marker. It's just the map.

**Comment by aitboudad** [comment]
@jorgelub12 fixed!

**Comment by jorgelub12** [comment]
@aitboudad  Thanks you !. What did you changed if I can ask?

**Comment by aitboudad** [comment]
the script [markerclusterer.ts](https://github.com/googlemaps/js-marker-clusterer/blob/gh-pages/src/markerclusterer.js) was missing

**Comment by jorgelub12** [comment]
@aitboudad  did you added some other dependence? Because I'm following the link that you sent and I got some errors like : 
```
Module not found: Error: Can't resolve 'markerclusterer' in 'D:\Projects\M\Frontend\src\app\components\views\map'
resolve 'markerclusterer' in 'D:\Projects\M\Frontend\src\app\components\views\map'
  Parsed request is a module
```

**Comment by aitboudad** [comment]
maybe you missed to include `markerclusterer.js` https://stackblitz.com/edit/angular-jbp2yc?file=markerclusterer.ts also ensure to import it using relative path example:
```ts
import './markerclusterer';
```

another way that may work is to remove `import 'markerclusterer';` from the app component and add [markerclusterer.ts](https://github.com/googlemaps/js-marker-clusterer/blob/gh-pages/src/markerclusterer.js) in you index.html page:

```ts
<script src="custom_path/markerclusterer/markerclusterer.js"></script>
```

**Comment by closer27** [comment]
@aitboudad Your solution was very helpful for me. Thank you

**Comment by plamen-redzhov** [comment]
@aitboudad The proposed solution unfortunately only works for standard Markers. Custom markers cannot be put in clusters. I've tried to find a way to implement the missing methods mentioned [here](https://stackoverflow.com/questions/8297456/google-maps-v3-clustering-with-custom-markers), but I've failed. Any input on the matter would be appreciated.

**Comment by sreeyashu** [comment]
Any further progress on having clusters with Custom markers?

**Comment by onmywayout** [comment]
> @aitboudad The proposed solution unfortunately only works for standard Markers. Custom markers cannot be put in clusters. I've tried to find a way to implement the missing methods mentioned [here](https://stackoverflow.com/questions/8297456/google-maps-v3-clustering-with-custom-markers), but I've failed. Any input on the matter would be appreciated.

It does work with custom Icons. I just tried myself. Taking custom icons as an example:

```
  const markers = this.longitudes.map((location, i) => new google.maps.Marker({
      position: location.LatLng,
      icon: ".//assets/img/rectangle.svg"
    })
    );
    );
```
If you mean, with custom marker icons, it works as well. You just need to provide an address (local or web) with 3 icons numbered 1.png 2.png and 3.png on it. For instance

```
`const markerCluster = new MarkerClusterer(event.target, markers,
      {imagePath: './/assets/img/'}

```

Thanks to @aitboudad , his code is a life saver. I just tried with the ngmap version 0.30.3 and marketclusterer 1.03 and it works like a charm
