### ISSUE TITLE
ng2-map aot compilation

### ISSUE THREAD

**Issue by day01** [ng2-ui/map#106]
**Steps to reproduce and a minimal demo**
The main set for reproducing a problem - using the marker. 
For reproduce, we need AOT compilation process.

**Current behavior**
AOT compilation in an external project requires visible properties. Based on your workaround for INPUTS properties I think it is necessary to use sth similar for OUTPUTS properties.
`
Error in bail mode: [at-loader] ./compiled/node_modules/ng2-map/dist/components/custom-marker.ngfactory.ts:123:53
    TS2339: Property 'animationChanged' does not exist on type 'CustomMarker'.
`
**Expected/desired behavior**
I can compile the project to AOT with ng2-map as a reference.

**Other information**

Maybe it is time to add INPUTS and OUTPUTS as a normal variable instead strings?

**Comment by allenhwkim** [comment]
What is your ng2-cli version?

**Comment by allenhwkim** [comment]
Regarding `Maybe it is time to add INPUTS and OUTPUTS as a normal variable instead strings?`, 

I thought it seemed not DRY, but I might be also wrong for the sake of code organization.

Also it would require a lot of work to change all. I don't mind if someone make PR for this.

@ng2-ui/map what do you think about this change?

**Comment by day01** [comment]
"@angular/compiler-cli": "2.4.9",
"@angular/compiler": "2.4.9",

> @ng2-ui/map what do you think about this change?

I don't have access to map :) (team members are private).

> I thought it seemed not DRY

maybe it is duplicate strings :) but in this place, I think it will be better than dynamic assignment properties as
`OUTPUTS.forEach(output => this[output] = new EventEmitter());`
If you would like to use an array as the element of FOREACH (for a cleaner purpose it still will be available).

**Comment by aitboudad** [comment]
AOT work as expected to me, @day01 can you please make the changes to reproduce your issue?

**Comment by day01** [comment]
maybe a dirty solution but I reproduce an error:
https://github.com/day01/ng2map_aot_bug

commands:
yarn
`npm run build:aot`

Let me know if you find sth.  I hope there is a bug on my side.

**Comment by alexabbott** [comment]
markers are also not showing up for me using aot: https://github.com/alexabbott/music-map-v3

**Comment by allenhwkim** [comment]
@alexabbott could you create a separate issue for that?

**Comment by day01** [comment]
https://github.com/day01/ng2map_aot_bug

Work correctly.
