### ISSUE TITLE
Marker Label does not work

### ISSUE THREAD

**Issue by ziXet** [ng2-ui/map#118]
Marker directive ignores label.

**Steps to reproduce and a minimal demo**
Please take a look at this: https://plnkr.co/edit/mWHHRPJtBoOcIozOATjy?p=preview

**Current behavior**
It does not show the label "A" on the marker.

**Expected/desired behavior**
I expect to see "A" on the marker.

**Comment by allenhwkim** [comment]
`[label]="'A'"`
or
     `label="A"`
