### ISSUE TITLE
Are Marker Updates Fully Supported?

### ISSUE THREAD

**Issue by ardywibowo** [ng2-ui/map#121]
Hello,
I was just wondering if updating markers is fully supported in this project. In Plunker, I was able to hardcode a few points, and when an event is triggered (pressing a button) the marker position was successfully changed. However, when I change the number of points contained within the map, I received an error stating `Cannot read property 'match' of undefined`. I did this change by assigning a different array of points to the map.

I appreciate any help you can give me.

Best regards,
Randy

**Comment by allenhwkim** [comment]
Thanks for the question
Marker updates are fully supported by design
Please create a plunker example to illustrate your issue

**Comment by ardywibowo** [comment]
I see. Thanks for the quick reply.
I just wanted some reassurance that this feature is supported. I assume it is supported for all layers such as the Heatmap Layer?

**Comment by ardywibowo** [comment]
OK,
So I was able to recreate my issue here:

https://plnkr.co/edit/yXHIhJ?p=info

It seems that assigning a new array to positions produces an error, but if I just change the contents of the original array created, it is fine. Is this intentional?

**Comment by allenhwkim** [comment]
Nope jot intentional

**Comment by allenhwkim** [comment]
For your case, `this.test` actually does not exist.
```
export class AppComponent {
  positions = [];
  teset = [];  //<--- You need to define this.
```

**Comment by zealitude** [comment]
@allenhwkim 

How about this
https://plnkr.co/edit/MW6xYAhaQf1oGMz9sGsd?p=preview

using mapClick to call addMarker() will not trigger map update
