### ISSUE TITLE
Polyline strokeColor cannot be changed dynamically

### ISSUE THREAD

**Issue by ziXet** [ng2-ui/map#122]
**Demo**
Please take a look at this Plunker: https://plnkr.co/edit/26RW7DJu8QWnRc4yWc4q?p=preview

**Current behavior**

  - Receiving error when the value of the variable that is assinged to strokeColor gets changed.

**Expected/desired behavior**

  - The color of the Polyline line should change

**Error**

  - TypeError: object[setMethodName] is not a function
    at Ng2Map.updateGoogleObject (main.bundle.js:8178)
    at Polyline.BaseMapDirective.ngOnChanges (main.bundle.js:7529)

**Comment by allenhwkim** [comment]
You can initialize it with all possible options. However, you cannot change all dynamically according to API.
https://developers.google.com/maps/documentation/javascript/reference#Polyline

Please use `setOptions` if not possible using the given API.

**Comment by ziXet** [comment]
Fair enough. setOptions did the job.

Thanks

**Comment by allenhwkim** [comment]
I may use this opportunity to update error message, so that this kind of issues can be well-guided by the error message. 
e.g. 
`ERROR: Not all options are dynamically updatable according to Googles Maps API V3 documentation. Please use "setOptions" instead`

**Comment by allenhwkim** [comment]
Closing, please add a star to this repo if you want to recommend it to others.

**Comment by adskiremote** [comment]
Apologies for asking this I've tried but unable to see how to setOptions for the strokeColor.  
Can anyone provide a brief instruction on how to access setOptions on the map?

**Comment by gregfrasco** [comment]
@adskiremote You can call setOptions by 
```ts
this.map.polylines[i].setOptions()
```
If you do not have the map in ts you can pass it in via 
```html
(mapReady$)="onMapReady($event)"
```

```ts
onMapReady(map) {
    this.map = map;
}
```
