### ISSUE TITLE
`console.log` upgrade

### ISSUE THREAD

**Issue by allenhwkim** [ng2-ui/map#125]
We need to build a controlled `console.log`.

Here is the suggestion from Allen.

1. create an object `Konsole` at `@ngui/utils` with static variables
  * Konsole.LOG_LEVEL
  * Konsole.DEBUG

2. convert all `console.log` to `konsole.log`

The following is an example of `Konsole.ts`
```
export class Konsole {
  static  ALL =   parseInt('11111',2);
  static    DEBUG = parseInt('00001',2),
  static    LOG =  parseInt('00010',2),
  static    INFO =  parseInt('00100',2),
  static    WARN =  parseInt('01000',2),
  static    ERROR = parseInt('10000',2),
  static   NONE =  parseInt('00000',2)

  static LOG_LEVEL = Konsole.INFO;

  logLevel: int = this.INFO;  
 
  doLog(logLevl) {
    let toLog = this.sysLogLevel ^ logLevel;

    if (toLog) {
      let method = 'log';
      switch(logLevel) {
        case this.LOG_LEVEL.DEBUG: method = 'debug'; break;
        case this.LOG_LEVEL.INFO:  method = 'info';  break;
        case this.LOG_LEVEL.WARN:  method = 'warn';  break;
        case this.LOG_LEVEL.ERROR: method = 'error'; break;
      }
      console[logLevel].apply(console, arguments);
    }
  }

  debug() { doLog(this.LOG_LEVEL.DEBUG, arguments); }
  log()   { doLog(this.LOG_LEVEL.LOG,   arguments); }
  info()  { doLog(this.LOG_LEVEL.INFO,  arguments); }
  warn()  { doLog(this.LOG_LEVEL.WARN,  arguments); }
  error() { doLog(this.LOG_LEVEL.ERROR, arguments); }

}
```

**Comment by allenhwkim** [comment]
@ngui/map please review this requirement

**Comment by IAMtheIAM** [comment]
Its a good method for doing it. I will discuss before making any PR in the future.

**Comment by allenhwkim** [comment]
Thanks @IAMtheIAM README.md has been updated
![image](https://cloud.githubusercontent.com/assets/1437734/24670575/9811dba0-193c-11e7-8fcb-7d33b44deb37.png)

**Comment by IAMtheIAM** [comment]
Very good, thank you :-)

If you need help with this `konsole.log` task, let me know and I will be of assistance where I can.

**Comment by allenhwkim** [comment]
Let's discuss it little. Members may want it to be `logger` instead of
`konsole`.

**Comment by IAMtheIAM** [comment]
In your other post you mentioned setting the log level like this:

1. konsole.LOG_LEVEL=konsole.DEBUG to control the logging level from console or the application

Where would one put that to set it from within their ng2 application, so that ngui/map knows how to pick it up? If its a global var, then I wonder if some people may already be using namespace `logger` for their own internal logging function within the app.

**Comment by allenhwkim** [comment]
@marrypen, vote for `logger`?
@IAMtheIAM, we need to instantiate `konsole` in the constructor. Using global variable is not recommended IMO.

**Comment by IAMtheIAM** [comment]
`import {konsole} from '@ngui/utils'` that is a good method, I would vote on that. (although I'm not a voting member yet). User can import into their `app.component.ts` and set it once for the app.

**Comment by allenhwkim** [comment]
@IAMtheIAM sorry, no progress yet. too busy dealing with bill-paying job.

**Comment by aitboudad** [comment]
instead of adding `konsole` I propose to remove console during our build see #151
