### ISSUE TITLE
infowindow does not wrk

### ISSUE THREAD

**Issue by anivaisu** [ng2-ui/map#127]
Here is something I tried

This is my code:

<ngui-map center="Brampton, Canada">
    <marker #mrker position="Brampton, Canada" 
      draggable="true" 
      (click)="clicked($event)">
    </marker>
    <info-window id="iw">
      lat: [[lat]], lng: [[lng]]
    </info-window>
  </ngui-map>

import { Component,ViewChild } from '@angular/core';
import { NguiMapComponent } from '@ngui/map';
  @Component({
    template: require('./app.html')
  })
  class AppCompoment {
   @ViewChild(NguiMapComponent)
   ngMap:NguiMapComponent;

   //@ViewChild('mrker')
   //marker:any;

    clicked(event) {
      let marker = event.target;
      this.ngMap.openInfoWindow('iw', marker, {
        lat: marker.getPosition().lat(), 
        lng: marker.getPosition().lng(),
      });
    }

I am getting this error:

Cannot read property 'openInfoWindow' of undefined

How can i fix this issue.

Kindly advice me,
Thanks

**Comment by allenhwkim** [comment]
`this.ngMap`, where did you set the value of `this.ngMap`?

Please the example linked from README.md
https://rawgit.com/ng2-ui/map/master/app/index.html#/simple-info-window

**Comment by allenhwkim** [comment]
closing this. Please reopen this if answer is not good enought.
