### ISSUE TITLE
Triggering upfront loading of google maps libs / no lazy loading

### ISSUE THREAD

**Issue by olivermuc** [ng2-ui/map#128]
Hi!

Is there any (elegant) way to trigger **direct loading of the google maps libraries**, and not have them being loaded with the first map being displayed?

Reason being: I need to access google maps libs to gain distance information between two locations and am using directly, their `DistanceMatrixService()` function. 

This happens when no map has yet been loaded, hence the need to trigger early loading of the libs.

Any thoughts?

**Comment by allenhwkim** [comment]
https://developers.google.com/maps/documentation/javascript/tutorial

Please use script tag to load api.   If already loaded, ng2-map does not load again.
```
<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY"></script>
```

**Comment by olivermuc** [comment]
Indeed, that's a possibility. 
I was hoping to use an existing method/call, to avoid having to hardcode it into the html.

Ideally a config option as part of the app.module init.
Or even an explicit call from an early loaded component would do.

The hardcoding option, would be my last resort.

**Comment by allenhwkim** [comment]
Please make use of this, https://github.com/ng2-ui/map/blob/master/src/services/api-loader.ts

**Comment by olivermuc** [comment]
Browsing through the src code, I did see this service, but couldn't get it to load the libs.
Can you pls provide an example?
Thx.

**Comment by allenhwkim** [comment]
It's exported, simple import will work. Oh. you got it. 

```
import { NgMapAsyncCallbackApiLoader } from '@ngui/map';
```
