### ISSUE TITLE
Unable to add points to heatmap

### ISSUE THREAD

**Issue by shermmyy** [ng2-ui/map#132]
<img width="650" alt="screen shot 2017-04-15 at 6 03 47 pm" src="https://cloud.githubusercontent.com/assets/5205459/25067063/0d1424d6-2206-11e7-9625-2479f5c67c85.png">

I want to add a point to the heatmap, but I am getting the error pictured above:

<ngui-map zoom="13" center="37.782551, -122.445368">
    <heatmap-layer [data]="points"></heatmap-layer>
</ngui-map>

addPoints(){
    this.points = [];
    this.points.push({ lat: 37.782551, lng: -122.445365 })
}

**Comment by shermmyy** [comment]
Looks like the issue is that I need to pass in a google.maps.LatLng() Object rather than just a simple js object. How would I go about that?

**Comment by shermmyy** [comment]
google object is defined after ready events....

**Comment by allenhwkim** [comment]
If you want to load google object, load it as early as possible.

https://github.com/ng2-ui/map/issues/128
