### ISSUE TITLE
Smooth animation for user location pin

### ISSUE THREAD

**Issue by adappter** [ng2-ui/map#136]
Hello again,

is it possible to have a smooth camera and pin animation when I'm using geolocations?
Currently it's laggy when the user moves and the map center position and pin postion are changing to the current user location.

Maybe there is a workaround or something else?

Thanks for your help

**Comment by allenhwkim** [comment]
I am not aware of those functionality, and this module does not provide that functionality.

**Comment by Creiger** [comment]
Hi as for pins it is possible to make it change location smoothly if you add css transition for it. I am not sure about map, but i would also try adding transition css to some container.
