### ISSUE TITLE
How to resize Google Map ??

### ISSUE THREAD

**Issue by yogeshpaisode** [ng2-ui/map#141]
I would like to resize google map dynamically. How can i achieved that

**Comment by JulioWar** [comment]
Hello @yogeshpaisode, I found a solution in the source code.

For the component `ngui-map` exist a event `mapReady$`. You can use this event to initialize a variable in your component and then make a function to trigger the resize event. this is my example: 

### VIEW
```html
<ngui-map class="margin-top" style="height:500px; width:100%;" [center]="center"
                    (mapReady$)="initMap($event)"
                    (mapClick)="onClickMap($event)"
                    [fullscreenControl]="true"
                    [fullscreenControlOptions]="{position: 'TOP_RIGHT'}"
          ></ngui-map>
```
 ### COMPONENT
```typescript
  initMap(event: any) {
    this.map = event;
  }
  
  refreshMap() {
    this.center = 'Costa Adeja';
    google.maps.event.trigger(this.map, 'resize');
  }
```
