### ISSUE TITLE
Grey map on modal view

### ISSUE THREAD

**Issue by moskam** [ng2-ui/map#146]
When map is opened in bootstrap modal window it's grey.

**Steps to reproduce and a minimal demo**
https://plnkr.co/edit/3jQXbW0dISiLdJe4yCdL?p=preview

**Current behavior**
Open modal and see grey map
![image](https://cloud.githubusercontent.com/assets/4164631/26105796/cfd83534-3a43-11e7-8a29-6d4e0ec035ad.png)

**Other information**

Probably it's related to resizing of the map, this problem was occurring in previous version of ngmap for AngularJS.

**Comment by aitboudad** [comment]
@moskam can you test if #147 solve the issue, please!

**Comment by Leanvitale** [comment]
Hello! i have the same problem, how i solve?

**Comment by aitboudad** [comment]
@Leanvitale just update your package into `0.18.1`

**Comment by allenhwkim** [comment]
Thanks @aitboudad

**Comment by Leanvitale** [comment]
Thank you very much! It worked

**Comment by moskam** [comment]
Yes, that seems to be solved, Plunker example works now, THANKS!!!
