### ISSUE TITLE
replicate directions of list with 10 location in Angular4

### ISSUE THREAD

**Issue by Leanvitale** [ng2-ui/map#148]
Hello! I try replicate this example in my project:

https://ngmap.github.io/#/!directions.html

I need to create the directions of a list with 10 locations, one behind another. How can I replicate this in Angular4? Because I think the example is in Angular.

Thanks!

**Comment by allenhwkim** [comment]
You need to write your own. The example is Angular1, and this component is written in Angular2. Although it's Angular, they are very different each other.

**Comment by Leanvitale** [comment]
Exactly, I need it for Angular. Is there no example I can follow? I do not know how to do it

**Comment by allenhwkim** [comment]
Sorry, there is no example so far.

**Comment by Leanvitale** [comment]
And when could there be an example of that style? I need it too much

**Comment by allenhwkim** [comment]
No plan so far.

**Comment by AdrianMrn** [comment]
Any chance this could be coming out soon?
Is this possible at all, or has the waypoint option not been implemented at all?
