### ISSUE TITLE
Doesn't allow numeric marker label... even if its passed a string containing a number

### ISSUE THREAD

**Issue by jaufgang** [ng2-ui/map#150]
When specifying a marker with a numeric label, the label doesn't appear, and error messages shows up in the console 
```InvalidValueError: setLabel: not a string; and no text property```

This error occurs even if i explicitly convert the number to a string like so:
```
<marker *ngFor="let location of locations; let i=index"
	[position]="{lat:location.lat,lng:location.lng}"
	[label]="(i + 1).toString()">
</marker>
```

This should just display the label string as passed, especially if it is passed a string.
It would be convenient if it could also accept a number type and convert it to a string.

**Comment by AJRdev** [comment]
Hi,
I tried something like that before and I couldn't call the function `toString()` from the attribute directly, what I did is calling a function in my component that did the same thing : 

```
export class AppComponent {
     getStringValue(val : number)
     {
         return (val.toString());
      }
}
```

That did the trick, I think it's a problem of scope that you have here.

Let me know how it goes !

Regards, 
Andre.

**Comment by jaufgang** [comment]
No, it's not a problem calling the toString() function.  
I was able to find a workaround by calling
`[label]="(i + 1).toString()+'\u200b' "`

`\u200b` is a zero-width-space character.  Appending that to the string prevents the string being converted back into a number and the label displays just fine.  

The problem is that the component for some reason converts the value into a number and throws an error because it doesn't want to accept numbers, even though i am actually passing it a string.

**Comment by AJRdev** [comment]
Oh allright my bad, glad you found that trick to fix it !

It's pretty weird that the component has that kind of behaviour though ..

**Comment by jaufgang** [comment]
Yup.

**Comment by allenhwkim** [comment]
@AJRdev ngui/map does not have parser for each Google object. It's for both users and for developers. It assumes that all Inputs are google object and try to parse everything as Google options. 

https://github.com/ng2-ui/map/blob/master/src/services/option-builder.ts#L57

You are seeing is the side effect of `JSON.parse('1')` -> 1
Of course, label must be string. For that case, we need to have an exception for marker only.

**Comment by AJRdev** [comment]
@allenhwkim Oh ok thanks for these clarifications ! I understand now why the parser had this kind of behaviour !

**Comment by xandedj** [comment]
Good Morning.

how do I style the label of the maracador, example take it out of the middle, put on top of the marker add backgound, fiddle in the font and everything?

Thank you very much in advance.

Exemple: https://www.google.com.br/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwiEp7Td7LjWAhUHlJAKHU-ECFoQjRwIBw&url=https%3A%2F%2Fpt.stackoverflow.com%2Fquestions%2F224532%2Flabel-titulo-fixado-no-marker-google-maps-api&psig=AFQjCNGPpOUS9uL6OVlmEA0CMpcaPs4bAA&ust=1506171564292940
