### ISSUE TITLE
Pushing to polyline array doesn't update in map

### ISSUE THREAD

**Issue by vanderburg** [ng2-ui/map#152]
If I have a map with a polyline:

`<polyline *ngIf="polylinePath?.length > 3" [path]="polylinePath"></polyline>`

I push to that array, polylinePath, and once I get the 4th element in there, the polyline is drawn, as I expect (Just using > 3 as an example, will happen with any value), but any new pushes won't be rendered. In the console, "Polyline initialization options" will show the full array, however.

**Steps to reproduce and a minimal demo**

I've created a Plunker that shows this [here](https://plnkr.co/edit/ymwwJfPbBEbckh3f6n2x?p=preview) (Just click on the map to push to the polyline array)

**Current behavior**

Only the polyline up to the point the *ngIf is triggered is shown

**Expected/desired behavior**

Future pushes to the array are not rendered

**Other information**

I've attempted change detection (detectChanges() and markForChange() and running in ngZone), since I'm sure it's related, but I can't seem to figure it out. My guess is that it's something simple (And silly) that I'm doing incorrectly.

**Comment by vanderburg** [comment]
I was able to create an ugly workaround with the following:

```
<polyline *ngIf="polylinePath?.length % 2 === 0" [path]="polylinePath"></polyline>
<polyline *ngIf="polylinePath?.length % 2 !== 0" [path]="polylinePath"></polyline>
```

This way as the length changes from an even to odd number, one polyline is removed and a new polyline with the points is added to the dom, which renders normally, as previously indicated. I don't like this workaround and I'm still convinced I'm doing something wrong with the way I was originally attempting to do this.

**Comment by vanderburg** [comment]
I realized I can track the object with `initialized$` and edit the polyline object directly, but that looks like it could get complicated when you have an unknown number of polylines, potentially having to use some kind of lookup table to track them all.

Kind of an ugly method. Ideally, I would push to my array bound to `[path]="array"` to have the object update and then use the different `(events)="event(event$)"` to be aware of changes (Until and unless two way binding is planned *crosses fingers for the future*)

**Comment by OscarCenito** [comment]
Any updates on this? Having the similar problem.

**Comment by vanderburg** [comment]
I'm not the most skilled coder ever, so this might be inefficient, but, this is how I'm handling it. In my view, have the following:

`<polyline *ngIf="control.object.positions?.length > 0" [path]="control.object.positions" [geodesic]="true" (initialized$)="onPolyInit($event, 'myObject')"></polyline>`

In my model, I have this:

```
public onPolyInit(event, name): void {
    if (name === 'myObject') {
        this.control.polyline.myObject = event.getPath();
        google.maps.event.addListener(event.getPath(), 'set_at', () => {
            const newMyObjectArray = event.getPath();
            let length = newMyObjectArray.b.length;
            for (let i=0; i < length; i++) {
                this.control.object.positions[i] = { lat: newMyObjectArray.b[i].lat(), lng: lat: newMyObjectArray.b[i].lng() };
            }

            this.control.object.positions.splice(length - 1);
}
```

There's a few things going on here. First, this.control.object is a reference to one polyline path in the object I'm working with. It can change, so I use it to not have to worry about indexes. When I switch the polyline I'm working with, I just load the new one into that object (Which also loads the line into the map).

Secondly, You cannot just store the new path array into the object, replacing the old one, for some reason (Which I'm sure makes sense to those more TypeScript savvy, but I don't understand) because when you do, it creates a new object that is initialized as a polyline (Which would be fine), but it doesn't fire the onPolyInit method, so you can't get to the object to add a listener to anymore.

Thirdly, after I've replaced the individual array elements with the for loop, I splice it to remove any that should no longer be there, in case I've removed some, etc.

I use 3 copies of this method, one for 'set_at', which handles moving of existing points in the array, one for 'insert_at', which handles creating new elements in the array and 'remove_at', which handles deleting points in the array.

If I want to manually insert a point into the array, I use that this.control.polyline.myObject reference, and do the following:

`this.control.polyline.myObject.push(event.latLng) // event comes from a map_click event`

All of this is fairly inelegant and would be better handled by a more skilled coder, or by ng2-ui/map simply watching the referenced object in `[path]` (The preferred method), but it works.

**Comment by OscarCenito** [comment]
Thanks for the reply, though it feels incredibly unreliable to start using properties like "newMyObjectArray.b[i].lat()".  It would be great if it just worked out of the box, since it is a normal binding in angular, and you shouldn't have to do ugly hacks around it. Or if it doesn't work, a refresh function on the polyline object would suffice, to just set the path again.

**Comment by vanderburg** [comment]
To help clean this up, I discovered that there's a `getAt()` method, so you can instead use `newMyObjectArray.getAt(i).lat()`, etc, instead of accessing that `b` property directly. This is the functional equivalent to `event.getPath().getAt(i).lat()` and takes a numerical index as an argument.

I can easily remove points with the `removeAt(index)` method on polylines, but now I'm having some trouble deleting a vertex on a simple polygon (With one path). Try/catch doesn't produce an error, so I need to do some more analyzing of the object.

**Comment by OscarCenito** [comment]
Hey. I solved this issue by cloning the path and reassigning it, then the angular-binding updates the path on the map. 

` this.path = _.clone(this.path);`

Hope this helps you.

**Comment by vanderburg** [comment]
Does this fire the initialized event again so you don't lose the listeners?

**Comment by vanderburg** [comment]
@OscarCenito could you elaborate a bit on your cloning?

If I'm using <polygon [paths]="object.paths"></polygon>, I can't seem to find any method of putting data into the object after it's been initialized that will update on map, except for using the initialized$ event and doing .setPaths on that. The problem is that any time I replace object.paths (using object.paths = newPaths or any form of shallow or deep copying), and then do setPaths, it seems to be some other phantom polygon object that shows on the map (replacing the old one) but doesn't fire an initialized event.

The only way I can manage this at the moment is looping through the original object, updating the value by key, then trimming (if I remove a vertex). And touching of the entire object at once seems to break the map object entirely.

**Comment by allenhwkim** [comment]
Sorry, I haven't made time for this issue. Any volunteer?

**Comment by OscarCenito** [comment]
@vanderburg 
I use a service and I clone the path within the service when I get new data. From the component I just subscribe to an observable of the path, so I don't do anything specific regarding ng2ui-map component to solve the issue. That is how I did before too, so no chages in code regarding the component-part from my side.

**Comment by AdrianMrn** [comment]
Thanks @OscarCenito, your fix `this.path = _.clone(this.path);` worked for me 😄

**Comment by aitboudad** [comment]
angular doesn't track change of an input when using push you must pass a new ref:

```patch
-- this.polylinePath.push({ lat: event.latLng.lat(), lng: event.latLng.lng()});
++ this.polylinePath = [....this.polylinePath, { lat: event.latLng.lat(), lng: event.latLng.lng() }];
```

**Comment by vanderburg** [comment]
Thank you @aitboudad, this was really helpful. It does appear to create a new problem, however. If I have event listeners (insert_at, set_at, remove_at) based on the polygon created by the map, with an  `initialized$` event, then I use the spread operator like you describe, it looks like the map is creating a new shape (Which does show properly on the map now), but the listeners I created in that `initialized$` event no longer work, and that `initialized$` event doesn't fire again to give me the polygon object.

I also fully accept I could be doing something very wrong.

**Comment by aitboudad** [comment]
@vanderburg ok then, instead of spread operator you may use `changeDetectorRef.markForCheck()` see https://stackblitz.com/edit/angular-agz9ke

**Comment by vanderburg** [comment]
@aitboudad I may not have explained it properly, though, I appreciate your assistance anyway. I forked your stackblitz to better explain what's going on: https://stackblitz.com/edit/angular-by7ntf The polygon starts with 4 points and if you move any of the points, the set_at event fires correctly. If you then add a point and the array updates correctly, the new point is properly shown on the map, but the set_at event no longer fires if you try to move a point and it no longer updates the polygonPath. The click event, however, still does (proving it's still the same object, at least, I think).

This could certainly be a Google Maps API issue, I just don't know (potentially pebkac, too). I guess for now, I'm resigned to somehow separate the array I care about, in my application's object, and the actual shape path being used (Maybe by creating a dummy array that's only used to initialize the shape, then only editing my real array and the shape object manually, I'm not sure yet, but it's doable.)

**Comment by aitboudad** [comment]
here is another better approach https://stackblitz.com/edit/angular-ejnesk :),
`initPoly` is called only once, so instead why not just add the new path using google map api:

```ts
  addPolygonPoints(event) {
    this.polygon.getPath().push(event.latLng);
  }
```

**Comment by vanderburg** [comment]
That's an excellent suggestion, and I just needed the 'insert_at' event to update the polygonPath array (for some reason, updating the polygon object first doesn't cause the events to break. The shape appears to be pretty fragile, so if I wanted to have some sort of collaborative map editing (Like two people able to move points at the same time), I have to do something convoluted like the following with the new set of coordinates from the database to prevent it all from breaking):

(this.shapeObjects.courseBounds is the polygon, dbCourse.courseBounds is the new array from the DB and I'm using insert_at, remove_at and set_at events to update the local array)
```
const lengthDifference = this.shapeObjects.courseBounds.getPath().length - thisCourse.courseBounds.length;

if (lengthDifference > 0) {
    for (let i = 0; i < lengthDifference; i++) {
        this.shapeObjects.courseBounds.getPath().removeAt((this.shapeObjects.courseBounds.getPath().length - 1));
    }

}
if (lengthDifference > -1) {
    for (let i = 0; i < thisCourse.courseBounds.length; i++) {
        this.shapeObjects.courseBounds.getPath().setAt(i, new google.maps.LatLng(thisCourse.courseBounds[i].lat, thisCourse.courseBounds[i].lng));
    }
}
if (lengthDifference < 0) {
    for (let i = 0; i < this.shapeObjects.courseBounds.getPath().length; i++) {
        this.shapeObjects.courseBounds.getPath().setAt(i, new google.maps.LatLng(thisCourse.courseBounds[i].lat, thisCourse.courseBounds[i].lng));
    }
    for (let i = this.shapeObjects.courseBounds.getPath().length; i < thisCourse.courseBounds.length; i++) {
        this.shapeObjects.courseBounds.getPath().push(new google.maps.LatLng(thisCourse.courseBounds[i].lat, thisCourse.courseBounds[i].lng));
    }
}
```

It feels like a workaround, and it's kinda ugly, but it works and lets me just move on to other stuff for now, so I'll use it.

Thanks for your help, this has had me to some head banging on my desk.

**Comment by vanderburg** [comment]
If anyone is following along with this closed issue that certainly no one is reading anymore ( :) ), if you wish to use an array of arrays in a polygon (for a complex shape, or one with a hole, or something) and you want to add a new array, you can do it with: `polygon.getPaths.push(new google.maps.MVCArray([event.latLng]);`

You can catch this with an event:

```
google.maps.event.addListener(event.getPaths(), 'insert_at', (index) => {
    this.polygonPath.splice(index, 0, [{
        lat: event.getPaths().getAt(index).getAt(0).lat(),
        lng: event.getPaths().getAt(index).getAt(0).lng(),
    }]);
    this.initPolygon('polygonName', event);
});
```

You'll want to run the initPolygon if you have a for loop adding listeners to event.getPaths().getAt(i) so that you create the listeners for this new array within the polygon. You can create the listener inside the listener I provided above, but that gets...messy.


ALSO, slightly related, (@aitboudad, you may be interested to know) I discovered that it DOESN'T destroy the listeners when changing the array when you do the following (for general shapes I was discussing in previous posts above):
```
this.polygonPath = [];
setTimeout(() => {
    this.polygonPath = [...newPolygonPath];
}, 0);
```
This also doesn't cause initPolygon to be triggered again by the `(initialized$)` event, but the events continue to just...work. In a perfect world, two-way binding on `[paths]` would just work automagically, but I'm starting to get the hang of it. Thanks for the framework that frustrates me less and less each day. ;)
