### ISSUE TITLE
how to display info window on click of custom marker

### ISSUE THREAD

**Issue by ramrealpage** [ng2-ui/map#154]
I am trying to use custom marker and want to show info window on click of custom marker. But not able to show. is there any way I can achieve this.

**Steps to reproduce and a minimal demo**

  - _What steps should we try in your demo to see the problem?_
open the custom marker example and click on marker and add info window. info window is not displayed.
  - _Plunker example_
  - _If you cannot reproduce an issue with a plunker example, it's your environmental issue_

**Current behavior**
I am not able to show info window on click of custom marker.
  - 

**Expected/desired behavior**
I should be able to show custom window
  - 

**Other information**

  -

**Comment by santiago-alvarez-ruiz** [comment]
Same issue here. :(
I tried with the normal markers code, but it does't work.

**Comment by rainmak33r** [comment]
Any updates on this one ?

**Comment by nat2k5us** [comment]
Looking forward to a solution to this -

**Comment by allenhwkim** [comment]
sorry, I haven't had time for it. I will look into it.
*The fact is that custom marker is still a marker, and the InfoWindow must work the same.

**Comment by allenhwkim** [comment]
This is the working version without any code change, https://plnkr.co/edit/IeCiaO?p=preview
```
  @ViewChild(NguiMapComponent) nguiMapComponent: NguiMapComponent; 
  
  clicked(e) {
    console.log('this.nguiMapComponent', this.nguiMapComponent);
    this.nguiMapComponent.openInfoWindow('iw', this.customMarker);
  }
  
  onCustomMarkerInit(customMarker) {
    this.customMarker = customMarker;
    console.log('this.customMarker', this.customMarker);
  }
```

**Comment by allenhwkim** [comment]
This is the working version. https://plnkr.co/edit/IeCiaO?p=preview.
The key here is to get the map component instance correctly and use it to open infowindow.
```
  
  @ViewChild(NguiMapComponent) nguiMapComponent: NguiMapComponent; 
  pos = {lat: 1, lng: 2};
  
  clicked(e) {
    console.log('this.nguiMapComponent', this.nguiMapComponent);
    this.pos = {
      lat: this.customMarker.position.lat(), 
      lng: this.customMarker.position.lng()
    };
    this.nguiMapComponent.openInfoWindow('iw', this.customMarker);
  }
  
  onCustomMarkerInit(customMarker) {
    this.customMarker = customMarker;
    console.log('this.customMarker', this.customMarker);
  }
```

**Comment by Pescu** [comment]
This can not be used with multiple custom markers. Can we associate some information for each custom marker and use it on click event?

**Comment by jcphlux** [comment]
@Pescu This is how I got it working for multiple custom markers. I took what @allenhwkim posted and looked at what it was doing in the debugger and put this together.

html
```html
    <custom-marker *ngFor="let loc of Locations; let i = index" [position]="[loc.Latitude, loc.Longitude]" (click)="clicked(i)" (initialized$)="onCustomMarkerInit($event)">
        <div class="marker"></div>
    </custom-marker>
```

code
``` javascript
    customMarkers: any[] = [];
    
    onCustomMarkerInit(customMarker) {
        this.customMarkers.push(customMarker);
    }
    
    clicked(index: number) {        
        this.nguiMapComponent.openInfoWindow("iw", this.customMarkers[index]);
    }
```

**Comment by ivanblazevic** [comment]
To avoid array mapping you can get that object directly on click using template reference variable:

```
    <custom-marker
      #md
      (click)="showTooltip(md.mapObject)"
```
