### ISSUE TITLE
LIMIT TO 10 POSITIONS IN MARKER

### ISSUE THREAD

**Issue by becerriljc** [ng2-ui/map#157]
hello, i am using @NGUIMAP but in markers only i can display 10 fields. why?
 
<marker
                    *ngFor="let item of gatewaysMovil" 
                    position="{{item.loc}}"
                    [icon]="item.img"
                    (click)="showIWindow($event, item)">
 </marker>

**Comment by allenhwkim** [comment]
I assume your location is not LatLng, but a string, which causes google geo api to be called. Google geo api has its usage limit. Please use LatLng if you want to display unlimited positions
