### ISSUE TITLE
NgUiMap and NgUiMapComponent objects are always available in memory

### ISSUE THREAD

**Issue by rammohan201** [ng2-ui/map#159]
Each visit to maps page is creating new instance of NgUiMap and NgUiMapComponent. This is creating memory leaks. Is this already known issue?

**Steps to reproduce and a minimal demo**
Add Map in a page, an application having two atleast two routes.  visit the map page multiple times, check the number of instances of NgUiMap and NgUiMapComponent in memory tab. count is increasing each time.
**Current behavior**
Objects are not cleaned up which is creating memory leaks
  - 

**Expected/desired behavior**
Objects should be cleaned up properly.
  - 

**Other information**

  -

**Comment by aitboudad** [comment]
just tested on my side and it appear that `NgUiMap` and `NgUiMapComponent` cleaned up (see the screenshot)
![selection_096](https://user-images.githubusercontent.com/1753742/26981659-5b4aeb2c-4d25-11e7-940c-e816b53121af.png)

please ensure you use the latest version `0.18.1`

**Comment by ramrealpage** [comment]
![image](https://user-images.githubusercontent.com/28886658/26982082-dafa6616-4d54-11e7-8e39-4bb77f1ee748.png)
Please look at this image there are multiple instances of NgUiMap and NgUiMapComponent

**Comment by ramrealpage** [comment]
I am using "@ngui/map": "^0.18.1" in my package json

**Comment by ramrealpage** [comment]
![image](https://user-images.githubusercontent.com/28886658/26982200-419786b0-4d55-11e7-85dd-417507ea085f.png)
does it mean, some where in the API, reference is retained?

**Comment by aitboudad** [comment]
to know if object is retained or not you should try `comparison`:

![selection_097](https://user-images.githubusercontent.com/1753742/26982330-9f633aa6-4d27-11e7-8ae4-4a858fa9f44f.png)

**Comment by ramrealpage** [comment]
I can clearly see, number of instances are increasing for each visit of my maps page. when I navigate from maps page to other page, snapshot shows the NgUiMap and NgUiMapComponents, I feel they should have been cleaned up.  This is the clean up code I wrote in ngOnDestroy method. 
should I handle anything specifically?
oogle.maps.event.clearListeners(this.map, 'markerClicked');
    google.maps.event.clearListeners(this.map, 'mapClicked');

    if(this.map) {
      this.map.setMap(null);
      delete this.map;
      this.map = null;
      this.mapOptions = null;
      this.markers = [];
    }

     if(this.streetMap) {
      this.streetMap.nguiMapComponent.map = null;
      delete this.streetMap;
      this.streetMap = null;
      this.mapOptions = null;
    }

**Comment by ramrealpage** [comment]
I am using  below code
<ngui-map [options]="mapOptions" [center]="mapOptions.center" [zoom]="mapOptions.zoom" (window:resize)="onResize($event)"
  (mapReady$)="onMapReady($event)" [ngStyle]="{height:mapOptions.height,width:mapOptions.width}"
  >
<marker *ngFor="let m of markers" [position]="m.position" [icon] ="m.iconUrl" (click)="onMarkerClick($event)"  (initialized$)="onInitialized($event)"></marker>
<polygon *ngFor="let polygon of polygons" [paths]="polygon.boundaries" [strokeColor]="polygon.strokeColor" [strokeOpacity]="polygon.strokeOpacity"
  [strokeWeight]="polygon.strokeWeight" [fillColor]="polygon.fillColor" [fillOpacity]="polygon.fillOpacity"></polygon>
</ngui-map>

<ngui-map [center]="mapOptions.center" [ngStyle]="{height:mapOptions.height,width:mapOptions.width}" (window:resize)="onResize($event)"
 (mapReady$)="onMapReady($event)">
<street-view-panorama [position]="mapOptions.position" [pov]="{heading: 165, pitch: 0}" [addressControl]="mapOptions.addressControl"
  zoom="1" (initialized$)="onInitialized($event)"></street-view-panorama>
</ngui-map>

**Comment by aitboudad** [comment]
I can help only if you provide me a repo which demos the behavior

**Comment by rammohan201** [comment]
![image](https://user-images.githubusercontent.com/12894116/26983116-43f09f02-4d58-11e7-9391-af0b21ae03ef.png)
We can recreate this issue using demo examples. first click on street view then check the NgUiMap and NgUiMapComponent count then click on heat map then check then grab the heap snapshot and check the count. I could see count is increased. Please find Image
https://rawgit.com/ng2-ui/map/master/app/index.html#/street-view-panorama

**Comment by aitboudad** [comment]
I'm able to reproduce it now, I'll look into it soon!

**Comment by rammohan201** [comment]
I want to work with you to fix this issue. let me know if needed.

**Comment by aitboudad** [comment]
I didn't started yet on this, so why not! 
PR welcomed ;)

**Comment by rammohan201** [comment]
I feel it will take time for me to fix this issue. But I need this fix
urgently.

**Comment by aitboudad** [comment]
Don't worry I'll try to find some time early today to fix that issue.

**Comment by rammohan201** [comment]
ok. thank you

**Comment by aitboudad** [comment]
fixed in #160

**Comment by rammohan201** [comment]
Thank you. How can I use this code fix? 
I see the pull request is still open.

**Comment by aitboudad** [comment]
just update to `0.18.2`

**Comment by rammohan201** [comment]
do I need to write any clean up code in my component? cause still objects are not cleaned up in my project even after updating to 0.18.2. it is working in demo application of this git repo.

**Comment by rammohan201** [comment]
Hi, 
street view is having memory leaks. First launch the street view and then navigate to some other map say map with markers.
streetview map instances are not cleaned up
![image](https://user-images.githubusercontent.com/12894116/27008742-a50dbf2c-4e98-11e7-918c-8ddcdc2b3cad.png)

**Comment by rammohan201** [comment]
Hi, the issue still exists in street view maps. can you take a look?

**Comment by aitboudad** [comment]
fixed in `0.18.3`, please check it and let me know if it's resolved.

**Comment by rammohan201** [comment]
There are still memory leak issues are available, do you have time to check
those issues? issue no#163

**Comment by aitboudad** [comment]
not right now, maybe at the weekend

**Comment by rammohan201** [comment]
Ok.. is it possible to give some idea how to clean up zone tasks ?
Thanks

**Comment by aitboudad** [comment]
basically `ngZone.runOutsideAngular` can clean up zone tasks but I'm not sure
