### ISSUE TITLE
How do I get house information using my marker?

### ISSUE THREAD

**Issue by ancientbag** [ng2-ui/map#166]
I have some markers on houses, and I made a simple infowindow when clicking on them.
But it only displays "lat" and "lng" properties, so how do I get street and number of house via marker?
I've tried to use on marker click
`onMarkerClick = function(marker){
        console.log(marker.target.getPlace());
}`
but this returns 'undefined'

**Comment by allenhwkim** [comment]
Plz take a look at this.
https://developers.google.com/maps/documentation/javascript/examples/geocoding-reverse
