### ISSUE TITLE
ACCESSING MAP OBJECT WITHIN PROMISE OR .THEN FUNCTION SUCCESS

### ISSUE THREAD

**Issue by ravivit9** [ng2-ui/map#167]
How to access map instance and map marker within a construction function promise success part.  I am using geoFire to create markers on number of events like key_entered (add marker), key_exited (remove marker) etc.,

I am a bit struggling to get hold of map object within the geofire .then function and within that geoQuery.on() as listed below.

**Current behavior**
Unable to access map object within promise .then function

**Expected/desired behavior**
Would like to know how to get access of map object within promise .then function
 

**Other information**
```

`constructor(private ref: ChangeDetectorRef, private db: AngularFireDatabase) {
        locRef = db.list('geofire').$ref;
        GeoFirePromise.then(function(GeoFire: any) {
                    const geoFire = new GeoFire(locRef);
                    const geoQuery = geoFire.query({
                        center: [51.4871327, -0.1986925],
                        radius: 35.5
                    });
                    const onKeyEnteredRegistration = geoQuery.on("key_entered", function(key, location, distance) {
                   console.log(key + " entered query at " + location + " (" + distance + " km from center)"); 
                   //I WOULD LIKE TO ACCESS MAP OBJECT HERE TO ADD MARKERS. 
            });
       }); 
}`
```

**Comment by aitboudad** [comment]
to get the map instance use `mapReady$` output:
```ts
@Component({
  selector: 'my-app',
  template: `
    <ngui-map center="la, ca" (mapReady$)="setMap($event)">
    </ngui-map>
  `
})
export class AppComponent  {
  setMap(map) {
    // ...
  }
  ...
}
