### ISSUE TITLE
Use the method: getPhotographerPov()

### ISSUE THREAD

**Issue by minortom** [ng2-ui/map#168]
I got the Streetview Panorama [example](https://rawgit.com/ng2-ui/map/master/app/index.html#/street-view-panorama) running. I'm facing the problem that I can't find how to change the "pov" to use the  [**getPhotographerPov()**](https://developers.google.com/maps/documentation/javascript/streetview#StreetViewLocation) method.

The example code:
` <h1>Simple StreetView</h1>
  <ngui-map zoom="14" center="37.869260, -122.254811">
    <street-view-panorama
      position="37.869260, -122.254811"
      pov="{heading: 165, pitch: 0}"
      zoom="1"
    ></street-view-panorama>
  </ngui-map>
`

For example change it to this: 
pov="getPhotographerPov()"

What is the best way to achieve this? Thanks!

**Comment by allenhwkim** [comment]
Try to use `setPov(StreetViewPanorama.getPhotographerPov())` function manually

**Comment by minortom** [comment]
Thank you for your reply. I have trouble obtaining the StreetViewPanorama object.
This is my code:
`import { Component } from '@angular/core';
import { Platform } from 'ionic-angular';
import { ApiService } from '../../../app/services/api.service';
import { IonicPage, NavController, NavParams } from 'ionic-angular';
import { LoadingController } from 'ionic-angular';
import { Observable } from 'rxjs/Observable';
import * as moment from "moment";
import { StreetViewPanorama } from '@ngui/map';
@IonicPage({
	segment: "events-detail/:id"
})
@Component({
	selector: 'page-events-detail',
	templateUrl: 'events-detail.html',
	providers: [ApiService, StreetViewPanorama]
})
export class EventsDetailPage {
	constructor(public navCtrl: NavController, public loadingCtrl: LoadingController, public navParams: NavParams, public platform: Platform, private apiService: ApiService) {

	}
	public item:any;
	public mapLocation = "1,1";
	ionViewDidEnter() {
		this.item = this.navParams.get('data');
		if(!this.item) {
			this.apiService.getSafetyEvent({ noParams: this.navParams.get('id') }).subscribe(
				response => {
					this.item = response;
					console.log(this.item);
					this.mapLocation = this.item.latitude + "," + this.item.longitude;
				}, error => { }
			);
		}
	}
	onMarkerInit(map) {
		console.log(map.setPov(StreetViewPanorama.getPhotographerPov()));
	}



}
`

**Comment by minortom** [comment]
Found the answer:

```
changePov() {
		var _lat = this.item.latitude,
			_lng = this.item.longitude,
			streetViewMaxDistance = 10;

		var point = new google.maps.LatLng(_lat, _lng);
		var streetViewService = new google.maps.StreetViewService();
		var panorama = this.map;

		console.log(panorama);
		// We get the map's default panorama and set up some defaults.
		// Note that we don't yet set it visible.


		//panorama = spaces.map.map.getStreetView();

		streetViewService.getPanoramaByLocation(point, streetViewMaxDistance, function(streetViewPanoramaData, status) {

			if (status === google.maps.StreetViewStatus.OK) {

				var oldPoint = point;
				point = streetViewPanoramaData.location.latLng;

				var heading = google.maps.geometry.spherical.computeHeading(point, oldPoint);
				console.log(panorama.getPhotographerPov())
				panorama.setPosition(point);
				panorama.setPov({
					heading: heading,
					zoom: 1,
					pitch: 0
				});
				panorama.setVisible(true);

			} else {
				console.log("no streetview");
				// no street view available in this range, or some error occurred
			}
		});
	}
}
```

I did it via the StreetViewService. Found it [here](https://stackoverflow.com/questions/7068365/getting-the-pov-for-google-streetview-api)
