### ISSUE TITLE
HeatmapLayer issue

### ISSUE THREAD

**Issue by manoj-netlings** [ng2-ui/map#180]
hi i am trying to implement heat map layer but i am getting this issue "Cannot read property 'HeatmapLayer' of undefined" can you please help me out

Thanks

Manoj

**Comment by manoj-netlings** [comment]
@aitboudad

**Comment by aitboudad** [comment]
you should include `visualization` library in your google map url, see https://github.com/ng2-ui/map/blob/master/app/main.ts#L29-L32

**Comment by manoj-netlings** [comment]
The library is added but it is not working i am using agm also

**Comment by aitboudad** [comment]
ok can you provide us a reproduction issue using the following plunker example https://plnkr.co/edit/6e1qWK?p=preview

also make sure you use the latest version :) + check the example: https://rawgit.com/ng2-ui/map/master/app/index.html#/heatmap-layer

Thanks!

**Comment by manoj-netlings** [comment]
Thanks it worked basically i was also using AGM which was creating issue
