### ISSUE TITLE
Polyline path variable not updated on polyline vertice change / add from the map

### ISSUE THREAD

**Issue by dpalinic** [ng2-ui/map#189]
Hello,

Thanks for developing this great library. I have a problem with polyline edit though. I expected that `path` variable would be updated with new vertices when polyline is edited on the map (added new vertices or moved around). If that's not expected to happened, can you please advise which event to listen for polyline changes and how to retrieve new vertices?

**Steps to reproduce and a minimal demo**

1. Create a polyline with example from this page: https://rawgit.com/ng2-ui/map/master/app/index.html#/simple-polyline
2. Move vertices on the map or add new ones

**Current behavior**

1. `path` variable is not updated with new vertices

**Expected/desired behavior**

1. `path` variable should be updated with new vertices

**Other information**

Maybe my expectation is wrong, but I'm not able to figure out how to retrieve new vertices after the change to the polyline on the map. Some suggestion would be great. 

Thank you

**Comment by allenhwkim** [comment]
You need to use events of polyline and need to update path. https://developers.google.com/maps/documentation/javascript/3.exp/reference#Polyline

**Comment by dpalinic** [comment]
Actually I just managed it to work automatically. I created `path` variable as `MVCArray<LatLng>` and then vertices are in sync. Also it is possible to register for `set_at` event on `path` making it easy to use.
Thanks for the help @allenhwkim .

**Comment by vanderburg** [comment]
I realized you closed this, but just to follow up, you can do this.

In your polyline and polygon, you can have `(initialized$)="initPoly('identifier', $event)"` (I use an identifier to store the event in an object to call back whenever).

Then, you can do something like this: 

```
public initPolygon(name, event): void {
    this.editControl.shapes[name] = event;
    google.maps.event.addListener(this.editControl.shapes[name].getPath(), 'set_at', (index) => {
        // console.log('bounds set at');
        this.object[name].positions[index] = {
            lat: this.editControl.shapes[name].getPath().getAt(index).lat(),
            lng: this.editControl.shapes[name].getPath().getAt(index).lng()
        };
    });
}
```

The naming I'm using is kinda abstract, but hopefully you get the idea. set_at is for dragging and moving a point, but there's also insert_at for when you click on the point between vertices to create a new point and remove_at, for when undoing a point, or other removal of a point through the map.
