### ISSUE TITLE
set drawingMode = null in drawing manager

### ISSUE THREAD

**Issue by hesama110** [ng2-ui/map#190]
**IMPORTANT**
in my developing i need to set drawingMode as null but it is causing error in option builder what i need to do? 
as you can see her it can be null 
https://developers.google.com/maps/documentation/javascript/3.exp/reference#DrawingManagerOptions
Regards

**Comment by allenhwkim** [comment]
Please remove drawingMode options when you initialize the map.
```
    <drawing-manager
      [drawingControl]="true"></drawing-manager>
```

**Comment by hesama110** [comment]
what i am trying to is that by clicking on a button i am adding mouse down listener to map after that when mouse is down and it is moving i am reading latLng but it is not activate untill i push hand icon in drawingManager 
tthis way is working in javascript and Typescript i have problem with angular i will be happy to help :) 

```
export class AppComponent  {

 myDrawingMode = 'marker';

  @ViewChild(NguiMapComponent) map: NguiMapComponent;

constructor(){}

onTypeClick(event) {
    console.log(event);
    console.log(this.map.el);
    const mymap = this;
    google.maps.event.addDomListener(this.map.el, 'mousedown', function (e) {
      console.log(google.maps.event.hasListeners(mymap.map, 'mousedown'));
      console.log(e);
      const poly = new google.maps.Polyline({ map: mymap.map.map  , clickable: false });
      // move-listener
      const move = google.maps.event.addListener(mymap.map.map, 'mousemove', function (em) {
          poly.getPath().push(em.latLng);
          console.log(google.maps.event.hasListeners(mymap.map, 'mousemove'));
          console.log('mousemove e.latLng', em.latLng);
      });
       // mouseup-listener
       google.maps.event.addListenerOnce(mymap.map.map, 'mouseup', function (e) {
        google.maps.event.removeListener(move);
        google.maps.event.clearListeners(mymap.map.el, 'mousedown');
     
    });
    });
     this.myDrawingMode = event;

  }
}

/**Html code*/
<ngui-map 
    (mapClick)="onMapClick($event)"
    [options]="allmyOptions"
    (mapReady$)="onMapReady($event)" >
<drawing-manager
      [drawingMode]="myDrawingMode"
      [drawingControl]="true"
      [drawingControlOptions]="{
        position: 2,
        drawingModes: [ 'circle', 'polygon']
       }"
       
      ></drawing-manager>
</ngui-map>
    <button *ngFor="let type of drawerTypes" (click)="onTypeClick(type)" >{{type}}</button>


```

**Comment by allenhwkim** [comment]
//myDrawingMode = undefined;
try `undefined` instead.

**Comment by hesama110** [comment]
it is the same 
AppComponent.html:5 ERROR TypeError: Cannot convert undefined or null to object
    at OptionBuilder.webpackJsonp.../../../../@ngui/map/dist/services/option-builder.js.OptionBuilder.googlize (option-builder.js:88)
    at NguiMap.updateGoogleObject (ngui-map.js:35)
    at DrawingManager.webpackJsonp.../../../../@ngui/map/dist/directives/base-map-directive.js.BaseMapDirective.ngOnChanges (base-map-directive.js:53)
    at checkAndUpdateDirectiveInline (core.es5.js:10845)
    at checkAndUpdateNodeInline (core.es5.js:12349)
    at checkAndUpdateNode (core.es5.js:12288)
    at debugCheckAndUpdateNode (core.es5.js:13149)
    at debugCheckDirectivesFn (core.es5.js:13090)
    at Object.View_AppComponent_0._co [as updateDirectives] (AppComponent.html:12)
    at Object.debugUpdateDirectives [as updateDirectives] (core.es5.js:13075)

**Comment by allenhwkim** [comment]
It seems working for me.

**Comment by hesama110** [comment]
thanks @allenhwkim
