### ISSUE TITLE
Multiple API load

### ISSUE THREAD

**Issue by isametal88** [ng2-ui/map#192]
Hi guys,
thank you very much for this component. I just started using it and it seems to be very well designed.

I sadly have a problem and I hope you can help me. The application I'm building is huge and it's hard for me to provide an example. We are currently using another Google Maps component inside the application in order to have a Google Places Autocomplete. For this, we are loading the Google Maps API from index.html. 
In order to use your component, we are doing it inside of the App module, as the documentation explains. 
Of course, this double load is incorrect. So I tried both ways:
1) disabling the API load in index.html makes your component working properly, but the other one isn't working no more, unless I show a ng2-ui map first.
2) disabling the app module load, your component is not able to understand that the API is loaded (it's understandable, the internal api load callback is not in place), and this causes errors.

Is there a way to load the API I still haven't thought of? 

Thank you very much.

Isaia

**Comment by allenhwkim** [comment]
@isametal88 thanks for designing complement. I spent a lot of time for it. :)

I understand you issue, but please try to replicate this issue on plunker. e.g., one map without ngui/map and one with map.

**Comment by isametal88** [comment]
As I think you understood, this is not properly an issue with your component, but an integration issue.
All I need is a way to notify your component of the API load.
Building a proper example is very complicated right now. If it is required I can figure something out...

**Comment by aitboudad** [comment]
I have an idea to solve this, I'll open a PR tomorrow!

**Comment by aitboudad** [comment]
seems my approach doesn't work properly :(, @isametal88 can try to add google-map before the angular script without `async` attribute? basically it should work!
```patch
-- <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY" async defer></script>
++ <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY"></script>

```

**Comment by isametal88** [comment]
Hi,
my API load in index HTML doesn't use async. The problem is that this library requires to load API from app.module in order to work properly, but the api load is done only when the first component is shown.

Anyway, I solved my problem replacing the other Google Places Autocomplete component with the one offered by this library (I don't know why I didn't think about it earlier...).

Thank you anyway.
