### ISSUE TITLE
API specification needed

### ISSUE THREAD

**Issue by isametal88** [ng2-ui/map#193]
Hi guys,

I got crazy figuring out what my problem was, and I think a little note on the documentation is needed.
The Marker directive position may be an address or a latLng object, and custom marker is the same but with an important difference: the latLng for the Google Marker is a Json Object ({lat:45,lng:9}), while the one for the custom marker is an array ([45,9]). Both annotations are perfectly fine, but i think a specification is needed in the documentation.

Thank you anyway for this work.

Isaia

**Comment by allenhwkim** [comment]
Please do not assume any. this strictly follows Google maps API.

1. there is no API for this. Marker is a google marker, CustomMarker is an OverlayView. 
2. array and other values area accepted as a value of an attribute for convenience.

**Comment by isametal88** [comment]
Oh, you're perfectly right. I was a Google Maps specialist, but time has passed and I forgot OverlayView lack of setPosition.
My bad. :-)

**Comment by allenhwkim** [comment]
FYI,

https://github.com/ng2-ui/map/blob/master/src/components/custom-marker.ts#L65

**Comment by isametal88** [comment]
Exactly:
`if (position.constructor.name === 'Array') {
        this.position = new google.maps.LatLng(position[0], position[1]);
      } else if (typeof position === 'string') {
        let geocoder = new google.maps.Geocoder();`
The component assumes that the position is either a string or an array, but not a LatLng object (as other markers do).

**Comment by allenhwkim** [comment]
it also accepts LatLng object.
```
else if (position && typeof position.lng === 'function') {
        this.position = position;
      }
```

**Comment by isametal88** [comment]
{lat:45,lng:9} is a Json object that is accepted by markers but not by the component 

(position.lng === 'function') = false
