### ISSUE TITLE
How to find a specific marker?

### ISSUE THREAD

**Issue by miliu99** [ng2-ui/map#194]
Thanks for this nice map component. I have several markers in the map, and clicking the marker will make the InfoWindow show up, which is fine. Now, I also need to be able to make the InfoWindow show up when I click a link outside of map. So, how do I locate the marker? Without this, it just shows up in the last clicked position.

**Comment by allenhwkim** [comment]
`map.markers`? It's in README.md. Also you can find more examples here, https://rawgit.com/ng2-ui/map/master/app/index.html

**Comment by miliu99** [comment]
Okay, I didn't get a direct way to find a marker. Instead, inspired by README.md, I used onMarkerInit event to track them in code-behind. It works. Thanks.

**Comment by yossely** [comment]
`map.markers` returns `undefined` to me, and in [Google Map documentation](https://developers.google.com/maps/documentation/javascript/reference#Map) there's no property called `markers` or any method to get the markers.

**Comment by aitboudad** [comment]
@yossely see https://stackblitz.com/edit/angular-2rmsne

**Comment by aitboudad** [comment]
The example contains two way, the first one rely on `mapReady$` output and the last one use `ViewChildren`
