### ISSUE TITLE
Map type (satellite or Map) is disabled on Map

### ISSUE THREAD

**Issue by djamajo** [ng2-ui/map#198]
**IMPORTANT**
I integrated Google Map into my angular 2 project and set up the default map 

**Steps to reproduce and a minimal demo**

  1 - $ npm install @ngui/map @types/googlemaps --save
  2 - import { NguiMapModule} from '@ngui/map';
  3 - NguiMapModule.forRoot({apiUrl: 'https://maps.google.com/maps/api/js?key=MY_GOOGLE_API_KEY'})
4 - 

 ```
export class HomeComponent implements OnInit {
  lat: number = 5.333141;
  lng: number = -3.956271;
  allOptions = {
    center: {lat: this.lat, lng: this.lng},
    zoom: 12,
   mapTypeId: 'satellite',
    tilt: 45
  };
}
```

```
<ngui-map class="angular-google-map angular-google-map-container"
      [options] = "allOptions" center="5.333141, -3.956271">
 </ngui-map>
```
**Current behavior**

 Satellite icon and Map icon are disabled 
  - 

**Expected/desired behavior**
Enable Satellite icon and Map icon 
  - 

**Other information**

  -

**Comment by zwtokio** [comment]
> mapTypeId

[https://developers.google.com/maps/documentation/javascript/maptypes?hl=es-419](https://developers.google.com/maps/documentation/javascript/maptypes?hl=es-419)

**Comment by allenhwkim** [comment]
Please create a plunker example. It's easy to create one by just clicking a button on the examples.
Without it, this will be closed.
