### ISSUE TITLE
map.markers is undefined when loading markers via HTTP/API call

### ISSUE THREAD

**Issue by anthony-pinskey** [ng2-ui/map#200]
**Steps to reproduce and a minimal demo**

**Plunker Example**
http://plnkr.co/edit/zyiBFylbhl8dXYnwyjnV?p=preview

**Current behavior**
- When setting markers via an HTTP call, map.markers is returned as undefined in the mapReady$ event as shown in the console.log(map.markers). If you console.log(map) the markers are set though.

**Expected/desired behavior**
- map.markers needs to be available for use in initialization methods like ngOnInit lifecycle hooks.
- map.markers should be defined with the marker data set so that you can run logic on the initialized data when the app first loads such as setting the bounds or re-centering the map based on the marker positions.

If this is not the desired behavior, is there a recommended setup for setting the map markers via API/HTTP calls and being notified of when they are ready? This seems to be an issue when also trying to set the markers array in the ngOnInit lifecycle hook as well.

**Comment by allenhwkim** [comment]
You are checking markers when map is ready.
``` 
 onMapReady(map) {
    console.log('map', map);
    console.log('markers', map.markers);  // to get all markers as an array 
  }
```
You need to check markers when markers are ready using `initialized$` event. https://github.com/ng2-ui/map#how-to-get-a-instances-of-a-map-or-markers

**Comment by anthony-pinskey** [comment]
@allenhwkim Thanks! Doesn't the initialized$ event call every time though? Is there a way to trigger a method once all the markers have been added to the map?

**Comment by allenhwkim** [comment]
@anthony-pinskey yes, every time.  
AFAIK There is no way to this module know that all markers know but you.
You may look into other map events e.g., `idle`

**Comment by xandedj** [comment]
Good Morning

How can I, use a marker rotate?
