### ISSUE TITLE
Styles on map

### ISSUE THREAD

**Issue by albertocule** [ng2-ui/map#203]
Anyone knows how to apply styles ([like an array of objects](https://developers.google.com/maps/documentation/javascript/examples/maptype-styled-simple?hl=es-419)) with ngui-maps?

Thanks!

**Comment by ng-darren** [comment]
Hi, you could just inject it like any other parameters for ngui-maps like this:

`<ngui-map [zoom]="zoom"
    [styles]="config.mapStyle"
    (mapReady$)="onMapReady($event)"
    (mapClick)="mapClicked($event)">`

**Comment by hoisel** [comment]
@ng-darren It does not work for me.

**Comment by aitboudad** [comment]
see https://stackblitz.com/edit/angular-3cbdcq
