### ISSUE TITLE
how to rotate the icon according to the direction

### ISSUE THREAD

**Issue by xandedj** [ng2-ui/map#206]
how to use the rotate so that the maractor rotate according to the direction

**Comment by allenhwkim** [comment]
Please provide more details.

**Comment by xandedj** [comment]
Utilizo o icone de uma seta no mapa e o meu rastreador me passa um atributo chamado curso  com a direção em graus, ou seja um numero inteiro tipo 90, 180 e etc...

Preciso que a medida que esses valores foram passados a seta no mapa indique a direção de deslocamento, pode ser feito?

**Comment by hoangngk** [comment]
@allenhwkim 
Hi, I have the similar issue, I want my customized marker can rotate/turn as it is moving on the map. Can you please give some suggestions? The marker should work like Uber app. Thank you in advance.
