### ISSUE TITLE
Getting this error in the console whenever I try to run my app

### ISSUE THREAD

**Issue by shadobladez** [ng2-ui/map#208]
'ngui-map' is not a known element:
1. If 'ngui-map' is an Angular component, then verify that it is part of this module.
2. If 'ngui-map' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

is there any reason why I would get this type of error?

**Comment by aitboudad** [comment]
you cannot use `ngui-map` if it'is not part of the module itself except if you export it from the NgModule declaration:
```ts
 @NgModule({
   imports: [...],
   exports: [
      ...
      NguiMapModule,
   ],
 })
 export class SharedModule { }
```
