### ISSUE TITLE
Data Layer is not displaying

### ISSUE THREAD

**Issue by NoCopy** [ng2-ui/map#209]
This is based on the example provided in the https://github.com/ng2-ui/map repository:

**Steps to reproduce and a minimal demo**
https://rawgit.com/ng2-ui/map/master/app/index.html#/data-layer

**Comment by allenhwkim** [comment]
It seems Google DataLayer implementation has been changes.
Need to catch up with Google's change.

**Comment by aitboudad** [comment]
already fixed by #210
