### ISSUE TITLE
Not rendering in app.component.html

### ISSUE THREAD

**Issue by tejasrana95** [ng2-ui/map#221]
I tried to add it in html.

`<div class="">
                                <div class="google-map-container">
                                    <input places-auto-complete (place_changed)="placeChanged($event)" [types]="['geocode']" />
                                    <p>
                                        <ngui-map [center]="center"></ngui-map>
                                        place: {{address | json}}
                                    </p>
                                </div>
                            </div>`

It is not showing anything. Auto complete works fine.

When I add it directly through component.ts  like this:
`@Component({
  selector: 'my-app',
  template: `
    <ngui-map zoom="14" center="Brampton, Canada">
      <marker *ngFor="let pos of positions" 
        (click)="showInfoWindow($event)"
        [position]="pos"></marker>
    </ngui-map>
    <button (click)="showRandomMarkers()">Show Random Markers</button>
    <br/>
    <button (click)="addMarker()">Add Marker</button>
  `
})`

working fine.

**Comment by aitboudad** [comment]
the provided code is not clear, can you please put your example in https://stackblitz.com/edit/angular-xdef9i to see if I can help, thanks!
