### ISSUE TITLE
Is it possible to change the color of the default marker?

### ISSUE THREAD

**Issue by miliu99** [ng2-ui/map#223]
I know you can create custom markers. But I really like the default one, except that if I could change the color to blue, green or yellow and so on.

**Comment by allenhwkim** [comment]
You can use your own icon, https://stackoverflow.com/questions/11064081/javascript-change-google-map-marker-color

Closing this as out of scope.

**Comment by miliu99** [comment]
Okay, I got the idea, but I ran into a problem...I tried to use png image as icon - I clones the default icon (exactly same size 20x40 px). However, when I overlay the label on top of the marker, it is a little too low (the default works perfect). 

How can I adjust the vertical position of the icon or label so that they overlay nicely? I tried to use anchor property, but has no effect. Thank you very much.

**Comment by miliu99** [comment]
Never mind...I figured out myself...you can use labelOrigin to set position of the label within the marker.
