### ISSUE TITLE
Central marker disappeared after upgrade from 0.18.6 to 0.20.0?

### ISSUE THREAD

**Issue by miliu99** [ng2-ui/map#228]
Just upgraded to 0.20.0 and noticed the central marker disappeared. After restored v. 0.18.6 without changing anything else, the marker is back. Anybody else seeing this problem?

**Comment by aitboudad** [comment]
Hi, can you provide us a reproduction example using https://stackblitz.com ?

**Comment by miliu99** [comment]
Sorry for the delay, but when I try to create the project with ngui/map in stackblitz.com, the map doesn't show up and no error in console either. Anybody got a ready-to-run stackblitz with ngui/map so I can put my code in?

Anyway, I did some more research on this issue. Very strange...the exactly same code works in the for-loop, but not standalone.

```
<marker [position]="{lat: 34.0522342, lng: -118.2436849}" icon="{url:'assets/images/marker_red.png'}"></marker>
<marker *ngFor="let marker of markers;" [position]="{lat: 34.0522342, lng: -118.2436849}" [icon]="{url: 'assets/images/marker_red.png'}"></marker>
```

The first line shows nothing, but the second line works.

**Comment by aitboudad** [comment]
here is a ready stackblitz https://stackblitz.com/edit/angular-xdef9i, you can also provide us a repo using angular-cli if you want

**Comment by miliu99** [comment]
Thank you very much for the link, I just tried it. https://angular-xdef9i.stackblitz.io
I moved the center to la, ca, and then added a marker with an icon from google.

```
<ngui-map center="la, ca">
<marker [position]="{lat: 34.0522342, lng: -118.2436849}" icon="{url: 'http://maps.google.com/mapfiles/ms/icons/green-dot.png'}"></marker>  
</ngui-map>

```
the marker doesn't show up. If I remove the icon attribute, the default marker shows up.

**Comment by aitboudad** [comment]
it's work for me, you just need to use https over http and `icon` shoud be `[icon]`
```ts
<ngui-map center="Brampton, Canada">
  <marker position="Brampton, Canada" [icon]="{ url: 'https://maps.google.com/mapfiles/ms/icons/green-dot.png' }">
  </marker>
</ngui-map>
```
I updated the stackblitz example https://stackblitz.com/edit/angular-xdef9i too

**Comment by miliu99** [comment]
Okay, good catch. That's it. However, it worked in v.0.18.6 without the square brackets. Thank you very much.
