### ISSUE TITLE
Cannot read property 'initialized$' of undefined

### ISSUE THREAD

**Issue by becerriljc** [ng2-ui/map#230]
copy de example, then i have this error...
![iinit](https://user-images.githubusercontent.com/24251698/34016457-8e3f0d64-e0e7-11e7-9b6a-624f29946219.png)

**Comment by aitboudad** [comment]
Hi @becerriljc, can you provide us more details, it would be nice to provide a reproduction code using https://stackblitz.com or a repo using `@angular/cli`

**Comment by VlnRbn** [comment]
Hi, 
`@ViewChild(DrawingManager) drawingManager: DrawingManager;`
In ngOnInit  `this.drawingManager['initialized$'].subscribe(dm => { ... }` im getting the error Cannot read property 'initialized$' of undefined.
Any help is appreciated
@becerriljc  Please reply if you have solved the issue

**Comment by VlnRbn** [comment]
Hey, I have reproduced the bug in stackblitz 
It is because of using *ngIf 
[https://stackblitz.com/edit/angular-ng2ui-drawingmanager-error](https://stackblitz.com/edit/angular-ng2ui-drawingmanager-error)

**Comment by aitboudad** [comment]
you have to call the initialized part when `*ngIf` becomes true. for example:

```ts
toggleDrawshape() {
    this.drawshape = !this.drawshape;
    setTimeout(()=> {
      this.drawingManager['initialized$'].subscribe(dm => { ... }
    })
}
```
or use a setter for `drawingManager` to know when exactly when it's available, similar to https://stackoverflow.com/questions/39366981/angular-2-viewchild-in-ngif.

**Comment by VlnRbn** [comment]
Thanks for quick response,

this.selectedOverlay will remain undefined always. Please help me with the issue.

https://stackblitz.com/edit/angular-ng2ui-drawingmanager-error?file=src%2Fapp%2Fhello.component.ts
