### ISSUE TITLE
How to refresh the map after size has changed?

### ISSUE THREAD

**Issue by miliu99** [ng2-ui/map#231]
I have a list next to the map on right, if I hide the list, the map area is extended with empty space only. I have to click browser's refresh button to get the empty space filled. So, how do I make the map refresh automatically after resizing? Note that if the browser window is resized, it doesn't seem to have this problem.

**Comment by aitboudad** [comment]
@miliu99  can you try with https://github.com/ng2-ui/map/issues/141#issuecomment-300798823 and let me know if it solve your use-case.

**Comment by miliu99** [comment]
Yes, I saw that and tried it earlier, but it didn't work. The only thing works is hard refresh or 

        `window.location.reload();`
or
        `window.location.href = document.URL;`

Which is not only slow, but also has some other side-effects because I have other stuff on the same page.

**Comment by aitboudad** [comment]
ok @miliu99 can you replicate your example using  https://stackblitz.com/edit/angular-xdef9i ?

**Comment by miliu99** [comment]
Ok, I got the problem reproduced here: [https://angular-5husho.stackblitz.io](url)

**Comment by aitboudad** [comment]
@miliu99 see https://stackblitz.com/edit/angular-brp8az, you must add a timeout after toggling `showList`+ you must pass `$event` in onInit instead of `event`.

**Comment by miliu99** [comment]
It works great. You guys are really cool. Thanks a million.
