### ISSUE TITLE
I have a problem when I want to use angular 5

### ISSUE THREAD

**Issue by joseSierra94** [ng2-ui/map#234]
Have someone had this error, please if someone know about that could help to me
ERROR in node_modules/@ngui/map/dist/services/config.d.ts(1,10): error TS2305: Module '"/home/jose/projects/OpenMDM-FrontEnd-master/node_modules/@angular/core/core"' has no exported member 'OpaqueToken'.

this is my package.json:
{
  "name": "OpenMDM-FrontEnd",
  "version": "0.0.1",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update --standalone false --gecko false",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@agm/core": "^1.0.0-beta.2",
    "@angular/animations": "^5.2.0-beta.0",
    "@angular/cdk": "github:angular/cdk-builds",
    "@angular/common": "^5.2.0-beta.0",
    "@angular/compiler": "^5.2.0-beta.0",
    "@angular/core": "^5.2.0-beta.0",
    "@angular/forms": "^5.2.0-beta.0",
    "@angular/http": "^5.2.0-beta.0",
    "@angular/material": "github:angular/material2-builds",
    "@angular/platform-browser": "^5.2.0-beta.0",
    "@angular/platform-browser-dynamic": "^5.2.0-beta.0",
    "@angular/platform-server": "^5.2.0-beta.0",
    "@angular/router": "^5.2.0-beta.0",
    "@ngui/map": "^0.18.6",
    "@types/angular": "^1.6.39",
    "@types/core-js": "^0.9.41",
    "@types/googlemaps": "^3.30.2",
    "@types/jquery": "^3.2.17",
    "angular2-materialize": "^15.0.4",
    "angular2-tooltip": "^3.1.0",
    "angular2-translate": "^5.2.0",
    "core-js": "^2.4.1",
    "hammerjs": "^2.0.8",
    "jquery": "^2.2.4",
    "materialize-css": "^0.98.2",
    "md-tooltip": "0.0.1-alpha.1",
    "mdi": "^1.9.33",
    "ng2-charts": "^1.5.0",
    "ng2-materialize": "^1.8.0-beta.0",
    "ng2-stomp-service": "^1.2.2",
    "ng2-toastr": "^4.0.1",
    "rxjs": "^5.5.5",
    "socket.io-client": "^2.0.1",
    "sockjs-client": "^1.1.2",
    "stompjs": "^2.3.3",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.8.10"
  },
  "devDependencies": {
    "@angular/cli": "^1.1.2",
    "@angular/compiler-cli": "^5.2.0-beta.0",
    "@types/jasmine": "2.5.47",
    "@types/node": "^7.0.18",
    "angular-translate": "^2.15.1",
    "codelyzer": "~3.0.1",
    "jasmine-core": "2.6.1",
    "jasmine-spec-reporter": "4.1.0",
    "karma": "1.7.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.6.0",
    "protractor": "~5.1.1",
    "ts-node": "3.0.4",
    "tslint": "^5.2.0",
    "typescript": "^2.6.2"
  }
}

**Comment by aitboudad** [comment]
@joseSierra94 not sure if it's related to this package just ensure you use latest version of @ngui/map which is 0.20.1 and not 0.18.6
