### ISSUE TITLE
Get details of circle via drawing manager

### ISSUE THREAD

**Issue by tpiros** [ng2-ui/map#235]
How can I get the details of a circle drawn on the map via the Drawing Manager?

Consider this example: https://ng2-ui.github.io/map/#/drawing-manager

I'd like to get the details such as the centre point (lat, lon values) as well as the radius of the circle drawn.

**Comment by aitboudad** [comment]
you can get them from google map event, you can find more in google-maps docs:

```ts
google.maps.event.addListener(drawingManager, 'circlecomplete', function(circle) {
  const radius = circle.getRadius();
});

google.maps.event.addListener(drawingManager, 'overlaycomplete', function(event) {
  if (event.type == 'circle') {
    const radius = event.overlay.getRadius();
  }
});
```
