### ISSUE TITLE
How to render a list of Polygon inside a map using model as a source of data

### ISSUE THREAD

**Issue by dikey94** [ng2-ui/map#240]
Hi guys,
I'm trying to render a list of Polygon inside a map using model as a source of data. Everything works fine except that I can't load 'path' property from my model. I can use *ngFor for load every Polygon, but path binding is not working.
Do you have any examples?
Thanks!

**Comment by aitboudad** [comment]
hi, have a look at https://stackblitz.com/edit/angular-ejnesk
