### ISSUE TITLE
OverlayView Directive

### ISSUE THREAD

**Issue by jrsanchezalcala** [ng2-ui/map#241]
Needs implement directive OverlayView for cordova platform android project becouse markers are not render via <marker> becouse of a problem of cordova webview it has to use overlayview instead.

**Comment by aitboudad** [comment]
have you tried using CustomMarker (https://ng2-ui.github.io/map/#/custom-marker), which is an OverlayView.

**Comment by jrsanchezalcala** [comment]
I was trying my own custom Marker i did,t see it this thank you very much i
will try and i tell you



2018-02-01 18:03 GMT+01:00 Abdellatif Ait boudad <notifications@github.com>:

**Comment by jrsanchezalcala** [comment]
It works perfect . Maybe this is something that you should advise in documentation. Thank you for your help.

**Comment by aitboudad** [comment]
@jrsanchezalcala PR welcomed!
