### ISSUE TITLE
Change map language

### ISSUE THREAD

**Issue by jananigel** [ng2-ui/map#242]
is it possible to change map language when I click button to set language?  or add 'language=""' in api
Url and refresh the map (ngui-map)?
`app.module.ts`
> NguiMapModule.forRoot({
apiUrl: 'https://maps.googleapis.com/maps/api/js?key=API_KEY'
    })

`app.component.ts`
> onLanguageClick(){
    //I want change language here!
};

`app.component.html`
> <ngui-map id="map"
    (mapReady$)='onMapReady($event)'
    (mapClick)='onMapClick($event)'
    (idle)='onMapIdle($event)''>
</ngui-map>

**Comment by allenhwkim** [comment]
Try this way.
Try this way.
1. set apiUrl with a language `&language=kr`
2. redraw the map by destroying DOM and creating it again.

**Comment by jananigel** [comment]
Thanks for your reply!
Is app.module.ts can be changed at runtime?
(Sorry, it's my first time to create a map with Angular, it will simple if it's <script src = "api url&callback=initMap&langlage=kr"></script>, but in angular I don't how to change the apiurl at runtime.)

**Comment by jananigel** [comment]
Sorry...I still can't resolve this problem. I don't know how to change the apiUrl at runtime.
