### ISSUE TITLE
ERROR Error: Uncaught (in promise): Error: StaticInjectorError(AppModule)[Circle -> NguiMapComponent]: 

### ISSUE THREAD

**Issue by nickygencs17** [ng2-ui/map#243]
This is an odd error I can't seem to overcome. The component where the ngui-map is located works fine without any error. However, another component that does not have any ngui-map component I receive this error. 
<img width="788" alt="screen shot 2018-02-06 at 10 39 26 am" src="https://user-images.githubusercontent.com/19628012/35868311-24e291de-0b2a-11e8-8932-788ad74b1e46.png">

Please let me know what other additional information you need

**Comment by aitboudad** [comment]
Hi can you please provide a reproduction example, here is a starter [demo](https://stackblitz.com/edit/ng6-map-starter).
Thanks!
