### ISSUE TITLE
I can't initialize a `google.maps.places.Autocomplete` twice

### ISSUE THREAD

**Issue by AlBlanc** [ng2-ui/map#247]
See issue #245

**Comment by aitboudad** [comment]
hi, can you provide a reproduction example so I can understand your case,
here is a starter example: https://stackblitz.com/edit/ng-map-starter

**Comment by AlBlanc** [comment]
Hi @aitboudad,

I've just done this -> https://stackblitz.com/edit/ng-map-starter-idizoq

But I could not reproduce the bug. The issue should happen when you open twice the dialog, on the second time, the input does not have the place-auto-complete working.

I compared dependencies versions with my project and it is approximately the same... I come back to you once I find more details...

**Comment by aitboudad** [comment]
I can't reproduce it either.
