### ISSUE TITLE
Add Cluster Marker

### ISSUE THREAD

**Issue by becerriljc** [ng2-ui/map#249]
hi!
I would like to suggest the include of clustered google to not mix the library of google maps and ngui-map.

Thanks and regards!

**Comment by aitboudad** [comment]
not sure I understand what do you mean ? can you elaborate please.
there is an example of integration cluster marker with ngui-map see https://stackblitz.com/edit/angular-jbp2yc

**Comment by anuraggu** [comment]
it is not working.

**Comment by anuraggu** [comment]
please tell me how i show cluster and info window together. ?

**Comment by Deliforce** [comment]
> please tell me how i show cluster and info window together. ?

Hi,
Did you find any resource on this..? Even I'm facing the same issue.
help appreciated
Thanks
