### ISSUE TITLE
Unable to use a provider to supply signed API URL

### ISSUE THREAD

**Issue by VeteranCoder** [ng2-ui/map#254]
Hello,

This is more a request for information or help than a bug report, though it might end up being that.

I need to retrieve the (signed) API key from a provider on/after startup in Ionic 2 + Angular 5.  I do not see any way to do this.  The usage instructions state the API URL is supplied in app.module, and I don't see any way to use a provider property or function at that point to supply the URL + Key.

The sample:
```
  @NgModule({
   imports: [
     BrowserModule, 
     FormsModule, 
     NguiMapModule.forRoot({apiUrl: 'https://maps.google.com/maps/api/js?key=MY_GOOGLE_API_KEY'})
   ],
   declarations: [AppComponent],
   bootstrap: [ AppComponent ]
 })
```
I need to get the apiUrl from a provider.  How can I do that?

**Comment by aitboudad** [comment]
the config provider is `NG_MAP_CONFIG_TOKEN`:

```ts
constructor(@Inject(NG_MAP_CONFIG_TOKEN) config) {}
```
