### ISSUE TITLE
Change default timeout

### ISSUE THREAD

**Issue by fcpauldiaz** [ng2-ui/map#258]
https://github.com/ng2-ui/map/blob/1d8732ab2d404173aaeac0659f4fe3424ba9c3ac/src/services/navigator-geolocation.ts#L13

How can I change the timeout of the `geolocation.getPosition()` ? 
I see there are `geoLocationOptions` but I couldn't find any constructor that send the options.

**Comment by aitboudad** [comment]
just pass an object with `timeout` as an argument when calling `getCurrentPosition`:
```ts
navigatorGeolocation.getCurrentPosition({ timeout: 1000 });
```
