### ISSUE TITLE
has no exported member 'OpaqueToken'.

### ISSUE THREAD

**Issue by Vicky443** [ng2-ui/map#264]
ERROR in node_modules/@ngui/map/dist/services/config.d.ts(1,10): error TS2305: Module '"/Users/../Desktop/test/angular-admin/node_modules/@angular/core/core"'
 has no exported member 'OpaqueToken'.

{
  "name": "pd-free-angularcli",
  "version": "1.0.1",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^6.0.1",
    "@angular/common": "^6.0.1",
    "@angular/compiler": "^6.0.1",
    "@angular/core": "^6.0.1",
    "@angular/flex-layout": "^5.0.0-beta.14",
    "@angular/forms": "^6.0.1",
    "@angular/http": "^6.0.1",
    "@angular/platform-browser": "^6.0.1",
    "@angular/platform-browser-dynamic": "^6.0.1",
    "@angular/platform-server": "^6.0.1",
    "@angular/router": "^6.0.1",
    "@ngui/map": "0.18.3",
    "@ngui/ngui": "^0.15.2",
    "@types/googlemaps": "3.26.14",
    "arrive": "2.3.1",
    "bootstrap": "3.3.5",
    "bootstrap-notify": "3.1.3",
    "chartist": "0.9.4",
    "core-js": "2.4.1",
    "express": "4.15.3",
    "jquery": "1.12.4",
    "moment": "2.18.1",
    "rxjs": "^6.1.0",
    "rxjs-compat": "^6.1.0",
    "zone.js": "0.8.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.5.0",
    "@angular/cli": "6.0.1",
    "@angular/compiler-cli": "^6.0.1",
    "@types/bootstrap": "3.3.32",
    "@types/chartist": "0.9.34",
    "@types/jasmine": "2.5.38",
    "@types/jquery": "1.10.31",
    "@types/node": "6.0.73",
    "codelyzer": "2.0.0",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "3.2.0",
    "karma": "1.4.1",
    "karma-chrome-launcher": "2.0.0",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "0.2.0",
    "karma-jasmine": "1.1.0",
    "karma-jasmine-html-reporter": "0.2.2",
    "protractor": "5.1.0",
    "ts-node": "2.0.0",
    "tslint": "4.5.0",
    "typescript": "^2.7.2"
  }
}

**Comment by aitboudad** [comment]
see https://github.com/ng2-ui/map/issues/234#issuecomment-352915709
