### ISSUE TITLE
No event typeid_changed is emitted

### ISSUE THREAD

**Issue by thomas-lack** [ng2-ui/map#266]
**Steps to reproduce and a minimal demo**

  - Add `ngui-map` element to a template, specify an event handler for the  `typeid_changed` event
  - Change the type of the map, e.g. from roadmap to satellite
  - [Plunker example](https://plnkr.co/edit/jc6gvOGdgG5Nhjy79OYh?p=preview), a fork of the plunker example from the @ngui/map readme with additions to `app.component.ts`.

**Current behavior**

  - Event is not emitted, event handler is never called

**Expected/desired behavior**

  - Event handler is called when the maptype changes

**Other information**

  - The [googlemaps documentation](https://developers.google.com/maps/documentation/javascript/reference) shows an event called `maptypeid_changed`, but no event with the name `typeid_changed`
  - Changing the entry of the `OUTPUTS` array in `ngui-map.component.ts` from `typeid_changed` to `maptypeid_changed` seems to work

**Comment by aitboudad** [comment]
published a fix in `0.30.2`
